### Get all audit entries
GET localhost:8080/audit

### Create example audit entry
POST localhost:8080/audit
Content-Type: application/json

{
  "message" : "Something happened"
}

### Create intentionally wrong audit entry
POST localhost:8080/audit
Content-Type: application/json

{
  "message" : ""
}